POST http://localhost:8001/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

#### core
POST http://localhost:8000/login-by-token
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImV4cCI6MTc2ODgwMzM5NH0.o7D4sHRnnB2NrfFdUAzadZPCAz1JcvOu56nu3u4hWt0qPa5x2zkQY3CJh7c3gc_lHdtKPkdp49vfNdObG6x73MhCXNT07NDrvdXGJbEdaoO9j80VmE9abBpPw-8GAaRDZIOfISisPbTWglX46tQwhNFg0ucooR32FNeI8-jECY2KmM4cLaKGXM-Kah1vQ9CZr4PDZdmeP0LWSzAAd0_rYpNV3w9-rYoK_jJsNyTHt_CuMYh-piwiX5K0KRP1uMXmWUJSjBjzX5zFmY_g0k30HYUc0u0jjVKEvmpsmzmCBXbaW0Em6Lky8yJtXDds-sOKtwvNgdoGkf_dRhcvMUgeVg


#### logout
GET http://localhost:8000/logout

### LISTAR PRODUCTOS
GET http://localhost:8000/productos
Accept: application/json

###

### CREAR PRODUCTO
POST http://localhost:8000/productos
Content-Type: application/json

{
  "nombre": "Producto A",
  "precioActual": 150.50,
  "costoActual": 100.00,
  "activo": true
}

###

### ACTUALIZAR PRODUCTO
PUT http://localhost:8000/productos/2
Content-Type: application/json

{
  "nombre": "Producto A Modificado",
  "precioActual": 160.00,
  "costoActual": 110.00,
  "activo": true
}

###

### ELIMINAR PRODUCTO (Soft Delete)
DELETE http://localhost:8000/productos/2
Accept: application/json






#### crear usuario
POST http://localhost:8000/usuarios
Content-Type: application/json

{
  "username": "admin81",
  "password": "admin",
  "roles": ["ROLE_ADMIN"]
}
#### crear usuario directo
POST http://localhost:8001/service/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjb3JlIiwidHlwZSI6InNlcnZpY2UiLCJyb2xlcyI6WyJST0xFX1NFUlZJQ0UiXSwiaWF0IjoxNzY4ODQxMTY4LCJleHAiOjE3Njg4NDQ3Njh9.w-W6b6NFLmQl6nWT1WVcRN90OKsu6xdUHxYtH6rGJ6iJF4yfYlLtFeM31bsQf0Oo4hlYYdz4wUjA31EPbXOT_8oZRnJyx3JyH0qsPqipJaarps4oLO6_SGjFlgDD7fqXpgtncwM0b3dkPHmwgjSWGqn15nC35I31HvJ5bNczOpKw3GycC85w879u1IxfCPXB4wSizSRcPtryIOVzvb-9YBhaFHjZnmUYIZYkmVOM4pbjplfw4g93KISS2PdINpCHfbSixhdW3aaq0XEG6TZuMozvLyYJAa3RVXsu9jYg_Z387seBr7o3jUlIBEEg24FiW3KuHa9CiUs0hjBPSUC21A

{
  "username": "admin1",
  "password": "admin"
}

#### loguin service
POST http://localhost:8001/service/login
Content-Type: application/json

{
  "service": "core",
  "secret": "super-secret-core-key"
}

### CAJA: LISTAR FACTURAS EMITIDAS
GET http://localhost:8000/caja/facturas-emitidas
Accept: application/json

### CAJA: REALIZAR CIERRE
POST http://localhost:8000/caja/cerrar
Content-Type: application/json

### CAJA: LISTAR MOVIMIENTOS
GET http://localhost:8000/caja/movimientos
Accept: application/json
