POST http://localhost:8001/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

####
POST http://localhost:8000/login-by-token
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImV4cCI6MTc2ODY3ODU0NX0.uNwTkJPTYG6K2ZfhXwUXp1G5IFNld1QIJ2NcxA-If6TM7t0WF-5k6pq4zJUX0DoR-FYE_EMa8Zr0xux4UrMGBgnTM9sMf7X0svCIz3UA9Fhu2hzyjEcM5p6tazjaF3RCYAG_ZF5kUZ-rj_uejY6r-5LTUshDqhoGu0UczWX5yTxR1-N2y9PprxMPl2ajCJKQesfnrzAMScwGFhQ9DIp1VoxvQPXO1JhJDSUzv8f0hscgM-mk8L6Mkq1IPuCu4g44ItVvlp3yCBnG0W9XpI553pPZszmP1t0rzPnFDykzOWl3SaTlnoynDc14JRkic7sUkes9VReo0OAKzfP-Oy0axw
Content-Type: application/json


#### me
GET http://localhost:8000/me

#### logout
GET http://localhost:8000/logout

### LISTAR PRODUCTOS
GET http://localhost:8000/productos
Accept: application/json

###

### CREAR PRODUCTO
POST http://localhost:8000/productos
Content-Type: application/json

{
  "nombre": "Producto A",
  "precioActual": 150.50,
  "costoActual": 100.00,
  "activo": true
}

###

### ACTUALIZAR PRODUCTO
PUT http://localhost:8000/productos/2
Content-Type: application/json

{
  "nombre": "Producto A Modificado",
  "precioActual": 160.00,
  "costoActual": 110.00,
  "activo": true
}

###

### ELIMINAR PRODUCTO (Soft Delete)
DELETE http://localhost:8000/productos/1
Accept: application/json

