POST http://localhost:8001/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

####
POST http://localhost:8000/login-by-token
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImV4cCI6MTc2ODc4MTM1N30.T3lSXO4UOYTm0aPYb2_uyRFL_e3ulyOGmOw8bjU3fkOqyv2B1mj7vaSLhkiXD4YNxoj0c8BthW8gGUr4LLiXmVLJt5twaf_hy-lGBGkNDev4I2BsfN6YWzfjDa1N-z_ZyKUMaYs_Q-ipLEvGtjTtJBC4AQ6of9HMcBD0Z_MTaZz54QZEWkRUcthPovLsih82fOp-Lq87Z9vRYqHZJtp0BqvlLU5lPfTf7A2jjE76Ah_PGMkZ7Gc1HwXdIZ-GKhS0oH_ihBuBcrgypeQ7BwHcWg0SXa0PsjEztQtCIioxoondwwQSaet-sh81GtD1Ch3Xg_pstno9pbBFrI7Lu7JGRg

#### crear usuario
POST http://localhost:8000/usuarios
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin"
}

#### logout
GET http://localhost:8000/logout

### LISTAR PRODUCTOS
GET http://localhost:8000/productos
Accept: application/json

###

### CREAR PRODUCTO
POST http://localhost:8000/productos
Content-Type: application/json

{
  "nombre": "Producto A",
  "precioActual": 150.50,
  "costoActual": 100.00,
  "activo": true
}

###

### ACTUALIZAR PRODUCTO
PUT http://localhost:8000/productos/2
Content-Type: application/json

{
  "nombre": "Producto A Modificado",
  "precioActual": 160.00,
  "costoActual": 110.00,
  "activo": true
}

###

### ELIMINAR PRODUCTO (Soft Delete)
DELETE http://localhost:8000/productos/1
Accept: application/json


#### loguin service
POST http://localhost:8001/service/login
Content-Type: application/json

{
  "service": "core",
  "secret": "super-secret-core-key"
}
