<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260514120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crea inventarios e historial de movimientos';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE inventarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(150) NOT NULL, unidad_medida VARCHAR(20) NOT NULL, cantidad NUMERIC(12, 2) NOT NULL, costo_promedio NUMERIC(12, 2) NOT NULL, valor_total_actual NUMERIC(14, 2) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_eliminacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_655218ABE237E06 ON inventarios (nombre)');

        $this->addSql('CREATE TABLE inventario_movimientos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, inventario_id INT NOT NULL, tipo VARCHAR(30) NOT NULL, cantidad_anterior NUMERIC(12, 2) NOT NULL, cantidad_nueva NUMERIC(12, 2) NOT NULL, cantidad_delta NUMERIC(12, 2) NOT NULL, costo_anterior NUMERIC(12, 2) NOT NULL, costo_nuevo NUMERIC(12, 2) NOT NULL, usuario VARCHAR(150) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_actualizacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_eliminacion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7C89AD8A7645698E ON inventario_movimientos (inventario_id)');
        $this->addSql('ALTER TABLE inventario_movimientos ADD CONSTRAINT FK_7C89AD8A7645698E FOREIGN KEY (inventario_id) REFERENCES inventarios (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE inventario_movimientos DROP CONSTRAINT FK_7C89AD8A7645698E');
        $this->addSql('DROP TABLE inventario_movimientos');
        $this->addSql('DROP TABLE inventarios');
    }
}
