mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                factory: App\Infrastructure\Mercure\MercureTokenFactory
                publish:
                    - '%env(MERCURE_TOPIC_PEDIDOS)%'
